### ISSUE TITLE
LSD Frog is Gigantic

### ISSUE THREAD

**Issue by cpeddecord** [cpeddecord/rainbowfrog#5]
To better align our rainbowfrogs, we should resize our LSD Frog.

**Comment by jquatier** [comment]
:+1: this is really impacting my daily work.

**Comment by cpeddecord** [comment]
@JasonVeselka what's our ETA on this fix?

**Comment by cpeddecord** [comment]
@JasonVeselka

**Comment by JasonVeselka** [comment]
Shoot, didn't notice the first request for this... will get on it asap.
